[application]

# App (Project) Name
name = "local-achievements"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "static"

[web.app]
title = "Local Achievements"

[web.watcher]
reload_html = true
index_on_404 = true
watch_path = ["src", "static"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
