mod battlenet;
mod egs;
mod event;
mod location;
mod gog;
mod operation;
mod retro;
mod request;
mod result;
mod steam;

pub use battlenet::BattleNetOperation;
pub use egs::EpicGamesStoreOperation;
pub use event::RequestEvent;
pub use gog::GogOperation;
pub use location::FileLocation;
pub use operation::DataOperation;
pub use retro::RetroAchievementsOperation;
pub use request::DataRequest;
pub use result::DataOperationResult;
pub use steam::SteamOperation;
